apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-without-anti-affinity
  namespace: resilience-scheduling
  labels:
    app: app-without-anti-affinity
    module: pod-anti-affinity
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-without-anti-affinity
      module: pod-anti-affinity
  template:
    metadata:
      labels:
        app: app-without-anti-affinity
        module: pod-anti-affinity
    spec:
      containers:
        - name: app
          image: registry.k8s.io/pause:3.9
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
