apiVersion: v1
kind: Pod
metadata:
  name: pod-with-toleration
  namespace: resilience-scheduling
  labels:
    app: pod-with-toleration
    module: taints-tolerations
spec:
  nodeSelector:
    dedicated: resilience
  tolerations:
    - key: dedicated
      operator: Equal
      value: resilience
      effect: NoSchedule
  containers:
    - name: app
      image: registry.k8s.io/pause:3.9
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
