apiVersion: v1
kind: Service
metadata:
  name: hpa-container-app
  namespace: resilience-hpa
  labels:
    app: hpa-container-app
    module: hpa-container-metrics
spec:
  type: ClusterIP
  selector:
    app: hpa-container-app
    module: hpa-container-metrics
  ports:
    - name: http
      port: 80
      targetPort: http
